# Generated by Django 5.1.2 on 2024-10-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(default=None, upload_to='category_icons/'),
            preserve_default=False,
        ),
    ]
